server:
  port: 8082

spring:
  application:
    name: catalog-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog_db

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.checkoutline: INFO
